name: quick_pay_example
description: Demonstrates how to use the quick_pay plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  quick_pay:
    path: ../

flutter:
  uses-material-design: true