name: quick_pay
description: A Flutter plugin for QuickPay payments in your mobile application.
version: 1.0.0
author: Oleksandr Lysun
homepage: https://github.com/Oleksandr32/flutter-QuickPay
repository: https://github.com/Oleksandr32/flutter-QuickPay

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.oleksandr32.quick_pay
    pluginClass: QuickPayPlugin
